# Generated by Django 6.0.3 on 2026-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_creditbureaurequest_kyc_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbureaurequest',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('postal', 'Postal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creditbureaurequest',
            name='email_delivery',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='creditbureaurequest',
            name='postal_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
