# Generated by Django 6.0.3 on 2026-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creditbureaurequest_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbureaurequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
