# Generated by Django 6.0.3 on 2026-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_creditbureaurequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbureaurequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
