FROM python:3.12-slim

# ป้องกัน .pyc และทำให้ log ออกทันที
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# ติดตั้ง system dependencies สำหรับ psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# ติดตั้ง Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy project
COPY . .

# default command
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]